### ISSUE TITLE
古いrust-cryptoを捨てる

### ISSUE THREAD

**Issue by equal-l2** [equal-l2/rasppi-driver#13]
`rust-crypto`は2016年から更新がない<ruby>古<rt>イニシエ</rt></ruby>のcrateで、`rustc-serialize`や`gcc`などの古いcrateに依存していて良くない感じがする。

`rust-crypto`は現在では細かいcrateに分かれてOrganizationで管理されているらしい。
パスワードをハッシュする部分はこれ。
https://github.com/RustCrypto/password-hashing

**Comment by equal-l2** [comment]
ただしこっちのcrateにはpbkdf2の便利関数が(今のところ)ない。
(rust-cryptoから移植してプルリク送ってみるか?)

scryptoというやつなら便利関数があるのでそっちを使ってみるか？

**Comment by equal-l2** [comment]
こっちもありか？
https://github.com/Keats/rust-bcrypt

**Comment by equal-l2** [comment]
とりあえず`password-hashing`にプルリクを送ってみた
取り入れられたらそっちのcrateに移行する

**Comment by pfpacket** [comment]
:+1:

**Comment by pfpacket** [comment]
せっかくPRしたし、PBKDF2でも。まぁ、bcryptのほうがええんじゃというのがSOの相違らしいし、bryptoにするのもあり。

**Comment by pfpacket** [comment]
結局「できるだけ強固なハッシュ関数で、頻繁にメンテされてて、将来に渡ってそれが期待できて、利用者が多いライブラリの実装」を使用するのが吉。

**Comment by equal-l2** [comment]
今回投げたプルリクは完全にrust-cryptoのベタ移植なので、今ハッシュしてあるユーザ名・パスワードがそのまま使えて楽なんですな

**Comment by equal-l2** [comment]
正直Rustで暗号関係を扱う場合はOpenSSLのバインディングを使うのが(メンテナンスの頻度・信頼性から言って)一番いいのよね

**Comment by equal-l2** [comment]
[ring](https://github.com/briansmith/ring)もその観点で言えばいいのかな
(ringはBoringSSLを元にしているらしい)

**Comment by equal-l2** [comment]
`password-hashing`にPRがマージされました

**Comment by equal-l2** [comment]
リリースされたので 8a048f2 で移行しました
