### ISSUE TITLE
WASDキーで操作できるようにする

### ISSUE THREAD

**Issue by Aring8510** [equal-l2/rasppi-driver#5]
WASDキーで動いたら愉快だろうけれど，同時に押されないようにしなければならない．

**Comment by equal-l2** [comment]
グローバル変数で押されてるかどうかを管理すればできると思う

**Comment by equal-l2** [comment]
JavaScriptのイベントハンドラはキューに入って一つづつ順番に実行されるそうなので、競合状態にはならないはず
